### PR TITLE
Write premis.xml file only if validation succeeds

### LINKED ISSUE #32: Problem: SIP with a missing content directory errors without information in Enduro UI
**Describe the bug**

Christa uploaded a package with the following structure:

```
SIP_20240705_Vecteur_344423
└── header
    ├── content
    │   └── d_0000001
    │       ├── 00000001.jp2
    │       ├── ...
    │       └── Prozess_Digitalisierung_PREMIS.xml
    ├── metadata.xml
    └── xsd
        ├── ablieferung.xsd
        ├── ...
        └── zusatzDaten.xsd
```

It's missing the content directory that we would normally expect to find at the top level of the tree. Temporal shows that it was correctly identified (`"Type": "VecteurSIP"`) and that the content folder is missing (`[{"Failures":["Content folder is missing"]}]`). However, a few activities later, Enduro tried to create the premis.xml and save it to the content directory, resulting in a failure:

```
{
  "message": "lstat /var/lib/enduro/preprocessing/enduro1540872538/extract4239907984/SIP_20240705_Vecteur_344423/content: no such file or directory",
  "source": "GoSDK",
  "stackTrace": "",
  "encodedAttributes": null,
  "cause": {
    "message": "no such file or directory",
    "source": "GoSDK",
    "stackTrace": "",
    "encodedAttributes": null,
    "cause": null,
    "applicationFailureInfo": {
      "type": "Errno",
      "nonRetryable": false,
      "details": null
    }
  },
  "applicationFailureInfo": {
    "type": "PathError",
    "nonRetryable": false,
    "details": null
  }
}

And in the Enduro UI, none of the child workflow tasks are displayed:

![image](https://github.com/artefactual-sdps/preprocessing-sfa/assets/4612276/6441026b-adc6-46a9-8750-dc6607b2c4c3)


```

**To Reproduce**

1. Run the attached package
2. Review the Enduro UI and Temporal

**Expected behavior**

I expect to see the `Identify SIP structure` job displayed in the Enduro UI with a failure message indicating that the content directory is missing.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by djjuhasz**
Fixes #32.

Don't create the premis.xml file until after all validation activities have completed successfully. If validation is unsuccessful the premis.xml file is discarded with the rest of the working SIP, so any writes are lost anyway.

### CODE REVIEW

**Comment by djjuhasz** [comment]
This commit changes the format of the "Validate file format" PREMIS event slightly:
```
<premis:event>
    <premis:eventIdentifier>
      <premis:eventIdentifierType>UUID</premis:eventIdentifierType>
      <premis:eventIdentifierValue>ac70a209-7c4f-4c36-9774-1be1ce021a10</premis:eventIdentifierValue>
    </premis:eventIdentifier>
    <premis:eventType>validation</premis:eventType>
    <premis:eventDateTime>2024-09-06T23:19:21Z</premis:eventDateTime>
    <premis:eventDetailInformation>
      <premis:eventDetail>name=&quot;Validate file format&quot;</premis:eventDetail>
    </premis:eventDetailInformation>
    <premis:eventOutcomeInformation>
      <premis:eventOutcome>valid</premis:eventOutcome>
      <premis:eventOutcomeDetail>
        <premis:eventOutcomeDetailNote>Format allowed</premis:eventOutcomeDetailNote>
      </premis:eventOutcomeDetail>
    </premis:eventOutcomeInformation>
    <premis:linkingAgentIdentifier>
      <premis:linkingAgentIdentifierType valueURI="http://id.loc.gov/vocabulary/identifiers/local">url</premis:linkingAgentIdentifierType>
      <premis:linkingAgentIdentifierValue>https://github.com/artefactual-sdps/preprocessing-sfa</premis:linkingAgentIdentifierValue>
    </premis:linkingAgentIdentifier>
  </premis:event>
```

The <premis:eventDetail> value is now "name=&quot;Validate file format&quot;" where it used to be an empty string.

**Comment by djjuhasz** [comment]
Here's what the Enduro dashboard reports for a SIP missing the content directory:
image

File: internal/workflow/preprocessing.go [hunk 1]
```diff
@@ -384,3 +315,95 @@ func systemError(
 	r.Outcome = OutcomeSystemError
 	return r
 }
+
+func writePREMISfile(ctx temporalsdk_workflow.Context, root string, sip sip.SIP) error {
```
Comment (mcantelon) [inline internal/workflow/preprocessing.go:319]: Could this function possibly not have the "root" argument and instead use `sip.Path` internally? Or would their values possibly be different when this function gets called?

**Review by mcantelon — APPROVED** [review]
Nicely done... I had one question, but looks good overall!

We might want to remove `AppendEventXMLForSingleObject` from `internal/premis/premis.go` in this PR too (and its respective test) as that's probably no longer needed.

File: internal/workflow/preprocessing.go (hunk 1 above)
Comment (djjuhasz) [reply internal/workflow/preprocessing.go:319]: Oh yeah, that works. :+1:
