### PR TITLE
Don't rename Prozess_Digitalisierung_PREMIS.xml

### LINKED ISSUE #58: Problem: Prozess_Digitalisierung_PREMIS.xml should not append the parent directory name when moved to the metadata folder
**Describe the bug**

We thought it would be possible to include multiple dossiers in the same digitized SIP and appended the parent directory (dossier) name to avoid file name conflicts in the metadata directory.

**To Reproduce**

Ingest a digitized SIP type that includes a Prozess_Digitalisierung_PREMIS.xml file.

**Expected behavior**

Prozess_Digitalisierung_PREMIS.xml should be moved as it is to the metadata directory.

### PR DESCRIPTION
**Pull request by djjuhasz**
Fixes #58

Digitized (Vecteur) SIPs are the only type of SIP that contain a Prozess_Digitalisierung_PREMIS.xml file, and they will only ever contain a single dossier.  Because digitized SIPs only have a single dossier that contains a single Prozess_Digitalisierung_PREMIS.xml file there's no need to rename the file in the PIP to avoid name clashes.

Changes:
- Update the SIP identification logic - if a SIP has a Prozess_Digitalisierung_PREMIS.xml file then it must be a digitized SIP
- Add a SIP validation check to confirm that digitized SIPs only contain a single dossier
- Remove the SIP transformation code that renamed the Prozess_Digitalisierung_PREMIS.xml file

### CODE REVIEW

File: internal/activities/validate_structure.go [hunk 1]
```diff
@@ -74,6 +74,22 @@ func (a *ValidateStructure) Execute(
...
+			return nil, fmt.Errorf("ValidateStructure: check for unexpected dossiers: %v", err)
+		}
+
+		if len(entries) > 1 {
+			for _, entry := range entries[1:] {
+				failures = append(failures, fmt.Sprintf(
+					"Unexpected dossier: %s", entry.Name(),
+				))
+			}
+		}
```
Comment (jraddaoui) [inline internal/activities/validate_structure.go:90]: We don't know here which ones are the unexpected, if you want to show the directory names I'd show them all. Maybe "More than one dossier folder in the content directory: [list of directories]", or something like that. I also think not showing the list of directories is okay.

File: internal/activities/validate_structure.go [hunk 2]
```diff
@@ -74,6 +74,22 @@ func (a *ValidateStructure) Execute(
...
+		entries, err := os.ReadDir(params.SIP.ContentPath)
+		if err != nil {
+			return nil, fmt.Errorf("ValidateStructure: check for unexpected dossiers: %v", err)
+		}
+
+		if len(entries) > 1 {
+			for _, entry := range entries[1:] {
+				failures = append(failures, fmt.Sprintf(
+					"Unexpected dossier: %s", entry.Name(),
+				))
```
Comment (jraddaoui) [inline internal/activities/validate_structure.go:88]: This could go in one line. If not, I prefer to split each argument on its own line:

```go
failures = append(
    failures,
    fmt.Sprintf("Unexpected dossier: %s", entry.Name()),
)
```

File: internal/pips/pips.go [hunk 3]
```diff
@@ -42,20 +41,18 @@ func (p PIP) Name() string {
...
-	case filepath.Base(path) == "UpdatedAreldaMetadata.xml":
-		return filepath.Join("metadata", "UpdatedAreldaMetadata.xml")
-	case strings.HasPrefix(path, "content"):
+	switch name := filepath.Base(path); name {
+	case "Prozess_Digitalisierung_PREMIS.xml":
+		return filepath.Join("metadata", name)
+	case "metadata.xml":
+		return filepath.Join("objects", p.Name(), "header", name)
+	case "UpdatedAreldaMetadata.xml":
+		return filepath.Join("metadata", name)
```
Comment (jraddaoui) [inline internal/pips/pips.go:50]: `Prozess_Digitalisierung_PREMIS.xml` and `UpdatedAreldaMetadata.xml` could now go in the same case.

File: internal/sip/sip.go [hunk 4]
```diff
@@ -55,7 +54,7 @@ func New(path string) (SIP, error) {
 	if err != nil {
 		return s, fmt.Errorf("SIP: New: %v", err)
 	}
-	if len(f) > 0 && strings.Contains(strings.ToLower(s.Path), "vecteur") {
+	if len(f) > 0 {
```
Comment (jraddaoui) [inline internal/sip/sip.go:57]: Why are you removing this requirement?

**Review by jraddaoui — CHANGES_REQUESTED** [review]
Nice @djjuhasz, thanks!

We also need to change it in the `premis` package: https://github.com/artefactual-sdps/preprocessing-sfa/blob/main/internal/premis/premis.go#L380-L384.

File: internal/sip/sip.go (hunk 4 above)
Comment (djjuhasz) [reply internal/sip/sip.go:57]: I removed it because it didn't seem important to me — If the SIP contains a "Prozess_Digitalisierung_PREMIS.xml" file then it must be a digitized SIP whether or not it has "vecteur" in the name. Conversely if a SIP has a "Prozess_Digitalisierung_PREMIS.xml" file but doesn't have "vecteur" in the same then it shouldn't be identified as "born digital" SIP in my opinion.

Comment (jraddaoui) [reply internal/sip/sip.go:57]: @fiver-watson this was the requirement that checked for "vecteur" in the SIP name (that we made case insensitive). Is it okay to remove it? Not sure where it comes from.

Comment (djjuhasz) [reply internal/sip/sip.go:57]: @fiver-watson I'm just waiting on your response to @jraddaoui before submitting this PR for a final code review.

**Review by jraddaoui — APPROVED** [review]
